### PR TITLE
Added option to load scripts as embedded resources, added line ending normalized checksum option.

### PR DESCRIPTION
**Pull request by mhelleborg**
### The issue or feature being addressed

- This PR addresses [issue 30](https://github.com/lecaillon/Evolve/issues/30) and [issue 31](https://github.com/lecaillon/Evolve/issues/31)
We needed these features, but others might also want them too :).

### Details on the issue fix or feature implementation

- Rewrote to support the option to load embedded resources
- Added option for line ending normalization when calculating checksum
- Covered new features with unit tests

### Confirm the following

- [X] I have ensured that I have merged the latest changes from the master branch
- [X] I have included unit tests for the issue/feature
- [ ] I have included the github issue number in my commits
(the commits predate the issues..)

### CODE REVIEW

**Comment by GeirGrusom** [comment]
@lecaillon any plans on including this in a release? 😃

**Comment by lecaillon** [comment]
@GeirGrusom For now i'm struggling to make Evolve full .NET Core 2 compatible. It's a nice challenge ;)
I've planned a 1.8 version in a week or so. 
This issue could be discuss after I think. Say the 1.9. By the way could you please describe your use case about it in the #32 related issue ? It would help me better understand the context. Thx

**Comment by lecaillon** [comment]
@mhelleborg Hi, first of all thank you for your PR. There is a lot of good inside. I really appreciate the effort. 👍 

Actually I would have prefered two PR since I'm not sure embedded script #30 is a needed feature. I don't have feedback where have files in a script folder is a problem either on Windows or Linux. More over hide the scripts in the assembly goes against the simplicity and the transparency goal of Evolve IMO.

Concerning the normalisation of the line endings when calculating checksums #31 I totally agree. Thank's again for the feedback. However I would have applied the new checksum strategy by default to all migrations, and in case of failure, calculate it the old way. This way it simplifies the code and avoid the creation of a new configuration variable like: **NormalizeLineEndingsForChecksum**

What do you think ?

**Comment by mhelleborg** [comment]
@lecaillon Sure, I agree that it is absolutely a good idea just use a fallback check on mismatch. That will make using the newer version more painless on existing migrations, and less needed configuration options is better :)
In my experience, being able to embed scripts as resources simplifies a lot of use cases, especially when you do not know the environment it is being run in. Case in point, file references in the checksum test broke on the CI-server ;)

**Comment by lecaillon** [comment]
Do I make the changes in master for #31? (I release a 1.8.0 version this week)
Or do you want to push a new PR ?

**Comment by mhelleborg** [comment]
@lecaillon I dont have time to give you a separate PR on #31 right now, you can do the changes in master. But I really think #30 is useful too, and would improve the library.

**Comment by lecaillon** [comment]
@mhelleborg Ok. 
For #32 Duty noted ;) Let's talk about it for Evolve version 1.9.0

**Comment by lecaillon** [comment]
@mhelleborg I finally close the PR. All I needed is in the branch `add-embedded-resources-support`.
Thanks a lot for your help

**Comment by mhelleborg** [comment]
You're welcome!

Looking forward to using your new release instead of the fork :)

Den tor. 21. feb. 2019 kl. 09:39 skrev Philippe Lécaillon <
notifications@github.com>:

**Pull request closed without merging**
