### PR TITLE
Added cockroachdb support

### PR DESCRIPTION
**Pull request by jinhong-**

### CODE REVIEW

**Comment by lecaillon** [comment]
Cool, that is a really good start. (I can remove the local branch I was creating by my side ;) )

**Comment by jinhong-** [comment]
Let me know what else i can do to get this in quickly as i really need this for my current project

**Comment by lecaillon** [comment]
Added CockroachDB Evolve schema as database. Working on the tests now

**Comment by lecaillon** [comment]
@jinhong-  Well, Evolve finally supports CockroachDB v2 (with those kind of [limitations](https://www.cockroachlabs.com/docs/v2.1/online-schema-changes.html#limitations) in migration scripts). All 3 packages (Evolve, Evolve.CLI and Evolve.MSBuild) are updated. 

Last but not least, we need to be able to prevent multiple execution of Evolve. See: https://github.com/lecaillon/Evolve/issues/115#issuecomment-482007877

I'm gonna try to work on this but I really count on you for this part, since good knowledge of CockroahDB is mandatory.

**Comment by lecaillon** [comment]
Finally I've made it all work. With the lock part. If the design chosen is ok for you, I merge the PR

**Comment by lecaillon** [comment]
@jinhong- No news, good news

**Pull request merged**
