### PR TITLE
Resolved issue with .net 3.5

### PR DESCRIPTION
**Pull request by leonborko**
Thanks for helping out :+1:

Before submitting a pull request, please have a quick read through the [contribution guidlines](https://github.com/lecaillon/Evolve/blob/master/CONTRIBUTING.md) and provide the following information, where appropriate replace the `[ ]` with a `[X]`

### The issue or feature being addressed

- link to the issue/feature using it's github issue number #number (if an issue/feature does not exist, please create it first)

### Details on the issue fix or feature implementation

- provide some details here

### Confirm the following

- [x] I have ensured that I have merged the latest changes from the master branch
- [x] I have included unit tests for the issue/feature
- [ ] I have included the github issue number in my commits

### CODE REVIEW

**Comment by lecaillon** [comment]
Where is the issue concerning this PR ? Can you please be a lot more specific about your problem ?

**Comment by leonborko** [comment]
string.Concat(Path.GetFileNameWithoutExtension(script).Take(prefix.Length)) returns System.Linq.Enumerable+<TakeIterator>d__24`1[System.Char] String and compares with prefix which is V and that gives exception Prefix V not found in sql file name: <Path>\V1.0__pja_DispatchScannedItem-V2.sql

**Comment by lecaillon** [comment]
`String.Concat(IEnumearble<char>)` does not behave the same way in .NET 3.5 and .NET 4.5 ...
- In NET 3.5: it returns a sring representation of the type `IEnumerable<char>` : 

> System.Linq.Enumerable+<TakeIterator>d__3a`1[System.Char]

- In NET 4.5: it converts the chars to a string

**Comment by lecaillon** [comment]
Thank you for your help. Next time, please read the [contribution guidlines](https://github.com/lecaillon/Evolve/blob/master/CONTRIBUTING.md) and provide an issue associated with your PR.
Lucky us I think the #9 is all about that problem.

**Comment by lecaillon** [comment]
@leonborko When would you want me to release a new version of Evolve which include that fix ?

**Comment by leonborko** [comment]
I've build own, patched, version

**Pull request merged**
