### PR TITLE
Drop support of .net fwk

### PR DESCRIPTION
**Pull request by lecaillon**

### CODE REVIEW

**Comment by zellus** [comment]
Why did you drop support for .Net Framework?

**Comment by zellus** [comment]
I use 'Paket' as dependency manager. After upgrading to Evolve 3.0.0, Evolve.dll is not copied to the 'Release/Debug' folder anymore. 'net472' has been removed from the 'TargetFrameworks'.

**Comment by lecaillon** [comment]
I don't know Paket. Evolve is released with a netstandard2.0 version which is fully compatible with .NET framework 4.7.2+
If I create a console app in 4.7.2 and I add a reference to Evolve, the dll is copied in the output folder. Everything's fine.
Maybe Paket needs extra conf to support this scenario ?

**Comment by zellus** [comment]
I guess that removing 'net472' from `<TargetFrameworks>net472;netstandard2.0;net5.0</TargetFrameworks>` in 'Evolve.csproj' might be an issue for 'paket' at least.

**Comment by zellus** [comment]
I apologise for bothering you. After further investigation of the csproj file, I did find a 'hard coded' reference. Without the 'hard coded' reference, Evolve.dll is copied as expected.

**Comment by lecaillon** [comment]
Feel free to star the repo if Evolve is usefull to you ;)

**Comment by zellus** [comment]
Done, many thanks for your work!

**Pull request merged**
